export const CART_ADD_ITEM_TABLE_FAIL = 'CART_ADD_ITEM_TABLE_FAIL';
export const CART_ADD_TABLE_ITEM = 'CART_ADD_TABLE_ITEM';
export const CART_REMOVE_TABLE_ITEM = 'CART_REMOVE_TABLE_ITEM';
export const CART_SAVE_BOOKING_TABLE = 'CART_SAVE_BOOKING_TABLE';
export const CART_SAVE_TABLE_PAYMENT_METHOD = 'CART_SAVE_TABLE_PAYMENT_METHOD';
export const CART_TABLE_EMPTY = 'CART_TABLE_EMPTY';
